# These are supported funding model platforms

github: # Replace with your GitHub username
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# custom: # Add custom funding URLs

