name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.13"

      - name: Build package
        run: uv publish -v wheels/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.14.0